# Generated by Django 6.1.1 on 2026-09-13 06:26

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Вводный текст"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(verbose_name="Описание услуги"),
                ),
                (
                    "price",
                    models.CharField(
                        default="от 10 000 ₽", max_length=100, verbose_name="Стоимость"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="laptop",
                        max_length=50,
                        verbose_name="Иконка UIkit (например: laptop, cart)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
