# Generated by Django 6.1.1 on 2026-09-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фоновая картинка Hero",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(blank=True, verbose_name="Подзаголовок Hero"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок Hero"
            ),
        ),
    ]
