# Generated by Django 6.1.1 on 2026-09-13 08:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="intro",
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("quote", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "label": "Подзаголовок"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст (абзац)"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Одиночное изображение"},
                    ),
                    3: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"label": "Цитата / Важная мысль"},
                    ),
                },
                verbose_name="Контент статьи",
            ),
        ),
    ]
