# Generated by Django 6.1.1 on 2026-09-13 09:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogindexpage_intro_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Описание блога"
            ),
        ),
        migrations.DeleteModel(
            name="BlogPage",
        ),
    ]
